name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    shell: bash

jobs:
  static-analysis:
    name: Static analysis

    runs-on: ubuntu-latest

    steps:
      - name: Install
        run: |
          sudo apt update
          sudo apt install cppcheck

      - name: Clone
        uses: actions/checkout@v4

      - name: cppcheck
        run: cppcheck --std=c++17 src/

  code-format:
    name: Code format check

    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: clang-format
        run: find src -type f -name \*.cc -o -name \*.h | xargs clang-format --dry-run --Werror

  windows:
    name: Windows x64

    runs-on: windows-2019

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Cache cmake build
        uses: actions/cache@v4
        with:
          path: build
          key: windows-x64-cmake-v1

      - name: Configure
        run: |
          cmake \
            -B build \
            -G "Visual Studio 16 2019" \
            -A x64 \
            # EOL

      - name: Build
        run: |
          cmake \
            --build build \
            --config RelWithDebInfo \
            # EOL

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: fallout-ce-windows-x64
          path: build/RelWithDebInfo/fallout-ce.exe
          retention-days: 7
