name: Release

on:
  release:
    types:
      - published

defaults:
  run:
    shell: bash

jobs:
  windows:
    name: Windows x64

    runs-on: windows-2019

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Cache cmake build
        uses: actions/cache@v4
        with:
          path: build
          key: windows-x64-cmake-v1

      - name: Configure
        run: |
          cmake \
            -B build \
            -G "Visual Studio 16 2019" \
            -A x64 \
            # EOL

      - name: Build
        run: |
          cmake \
            --build build \
            --config RelWithDebInfo \
            # EOL

      - name: Upload
        run: |
          cd build/RelWithDebInfo
          7z a fallout-ce-windows-x64.zip fallout-ce.exe
          gh release upload ${{ github.event.release.tag_name }} fallout-ce-windows-x64.zip
          rm fallout-ce-windows-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
